"""initial domain schema"""
from alembic import op
import sqlalchemy as sa
import gymclaw.models

revision = '227579a5c228'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('handled_at', gymclaw.models.UTCDateTime(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id')
    )
    with op.batch_alter_table('agent_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_event_type'), ['type'], unique=False)

    op.create_table('calendar_event_snapshot',
    sa.Column('calendar_event_id', sa.String(), nullable=False),
    sa.Column('ical_uid', sa.String(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('end_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at_remote', gymclaw.models.UTCDateTime(), nullable=True),
    sa.Column('gymclaw_managed', sa.Boolean(), nullable=False),
    sa.Column('gymclaw_session_id', sa.String(), nullable=True),
    sa.Column('gymclaw_plan_revision', sa.Integer(), nullable=True),
    sa.Column('user_locked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('calendar_event_id')
    )
    op.create_table('crowd_observation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('observed_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_value', sa.Double(), nullable=False),
    sa.Column('normalized_value', sa.Double(), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learned_preference',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Double(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('first_observed_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('last_observed_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('planned_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('week_id', sa.String(), nullable=False),
    sa.Column('workout_template_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('planned_start_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('planned_end_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('prep_start_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('leave_home_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('expected_finish_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('calendar_event_id', sa.String(), nullable=True),
    sa.Column('crowd_prediction', sa.Double(), nullable=True),
    sa.Column('crowd_confidence', sa.Double(), nullable=True),
    sa.Column('user_locked', sa.Boolean(), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('created_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.CheckConstraint("status IN ('TENTATIVE','COMMITTED','STARTED','COMPLETED','CANCELLED','SKIPPED','MISSED')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_event_id')
    )
    with op.batch_alter_table('planned_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_session_week_id'), ['week_id'], unique=False)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('weekly_min_sessions', sa.Integer(), nullable=False),
    sa.Column('weekly_target_sessions', sa.Integer(), nullable=False),
    sa.Column('weekly_max_sessions', sa.Integer(), nullable=False),
    sa.Column('weekdays_allowed', sa.JSON(), nullable=False),
    sa.Column('minimum_full_rest_days_between_sessions', sa.Integer(), nullable=False),
    sa.Column('earliest_workout_start', sa.String(), nullable=False),
    sa.Column('latest_workout_finish', sa.String(), nullable=False),
    sa.Column('preferred_workout_minutes', sa.Integer(), nullable=False),
    sa.Column('minimum_workout_minutes', sa.Integer(), nullable=False),
    sa.Column('prep_minutes', sa.Integer(), nullable=False),
    sa.Column('commute_to_gym_minutes', sa.Integer(), nullable=False),
    sa.Column('commute_home_minutes', sa.Integer(), nullable=False),
    sa.Column('warmup_policy', sa.String(), nullable=False),
    sa.Column('default_compound_rest_seconds', sa.Integer(), nullable=False),
    sa.Column('default_accessory_rest_seconds', sa.Integer(), nullable=False),
    sa.Column('crowd_preference_weight', sa.Double(), nullable=False),
    sa.Column('calendar_preference_weight', sa.Double(), nullable=False),
    sa.Column('recovery_weight', sa.Double(), nullable=False),
    sa.Column('created_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.CheckConstraint('id = 1'),
    sa.CheckConstraint('weekly_min_sessions >= 0 AND weekly_min_sessions <= weekly_target_sessions AND weekly_target_sessions <= weekly_max_sessions'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('planned_session_id', sa.String(), nullable=True),
    sa.Column('started_at', gymclaw.models.UTCDateTime(), nullable=True),
    sa.Column('arrived_at', gymclaw.models.UTCDateTime(), nullable=True),
    sa.Column('completed_at', gymclaw.models.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('initial_eta', gymclaw.models.UTCDateTime(), nullable=True),
    sa.Column('final_eta', gymclaw.models.UTCDateTime(), nullable=True),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('crowd_feedback', sa.String(), nullable=True),
    sa.Column('waited_for_equipment_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crowd_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workout_session_id', sa.String(), nullable=False),
    sa.Column('observed_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.Column('normalized_score', sa.Double(), nullable=False),
    sa.Column('waited_for_equipment_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercise',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workout_session_id', sa.String(), nullable=False),
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('planned_working_sets', sa.Integer(), nullable=False),
    sa.Column('rep_min', sa.Integer(), nullable=False),
    sa.Column('rep_max', sa.Integer(), nullable=False),
    sa.Column('target_weight', sa.Double(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('substituted_from_exercise_id', sa.String(), nullable=True),
    sa.Column('deferred_reason', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING','ACTIVE','DEFERRED','COMPLETED','SKIPPED','SUBSTITUTED')"),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('set_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workout_exercise_id', sa.String(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('set_type', sa.String(), nullable=False),
    sa.Column('weight', sa.Double(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rir_optional', sa.Double(), nullable=True),
    sa.Column('logged_at', gymclaw.models.UTCDateTime(), nullable=False),
    sa.Column('rest_started_at', gymclaw.models.UTCDateTime(), nullable=True),
    sa.Column('rest_due_at', gymclaw.models.UTCDateTime(), nullable=True),
    sa.CheckConstraint("set_type IN ('WARMUP','WORKING')"),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('set_log')
    op.drop_table('workout_exercise')
    op.drop_table('crowd_feedback')
    op.drop_table('workout_session')
    op.drop_table('user_profile')
    with op.batch_alter_table('planned_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_session_week_id'))

    op.drop_table('planned_session')
    op.drop_table('learned_preference')
    op.drop_table('crowd_observation')
    op.drop_table('calendar_event_snapshot')
    with op.batch_alter_table('agent_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_event_type'))

    op.drop_table('agent_event')
    # ### end Alembic commands ###
